// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.0--rc3
// source: todogrpc/todogrpc.proto

package todogrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TodoCRUDClient is the client API for TodoCRUD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TodoCRUDClient interface {
	CreateTodo(ctx context.Context, in *NewTodo, opts ...grpc.CallOption) (*Error, error)
}

type todoCRUDClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoCRUDClient(cc grpc.ClientConnInterface) TodoCRUDClient {
	return &todoCRUDClient{cc}
}

func (c *todoCRUDClient) CreateTodo(ctx context.Context, in *NewTodo, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/todogrpc.TodoCRUD/CreateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoCRUDServer is the server API for TodoCRUD service.
// All implementations must embed UnimplementedTodoCRUDServer
// for forward compatibility
type TodoCRUDServer interface {
	CreateTodo(context.Context, *NewTodo) (*Error, error)
	mustEmbedUnimplementedTodoCRUDServer()
}

// UnimplementedTodoCRUDServer must be embedded to have forward compatible implementations.
type UnimplementedTodoCRUDServer struct {
}

func (UnimplementedTodoCRUDServer) CreateTodo(context.Context, *NewTodo) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTodo not implemented")
}
func (UnimplementedTodoCRUDServer) mustEmbedUnimplementedTodoCRUDServer() {}

// UnsafeTodoCRUDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoCRUDServer will
// result in compilation errors.
type UnsafeTodoCRUDServer interface {
	mustEmbedUnimplementedTodoCRUDServer()
}

func RegisterTodoCRUDServer(s grpc.ServiceRegistrar, srv TodoCRUDServer) {
	s.RegisterService(&TodoCRUD_ServiceDesc, srv)
}

func _TodoCRUD_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTodo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoCRUDServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todogrpc.TodoCRUD/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoCRUDServer).CreateTodo(ctx, req.(*NewTodo))
	}
	return interceptor(ctx, in, info, handler)
}

// TodoCRUD_ServiceDesc is the grpc.ServiceDesc for TodoCRUD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoCRUD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todogrpc.TodoCRUD",
	HandlerType: (*TodoCRUDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodo",
			Handler:    _TodoCRUD_CreateTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todogrpc/todogrpc.proto",
}
